### ISSUE TITLE
How does the function connect to the kafka instance?

### ISSUE THREAD

**Issue by michaelmok2021** [schacko-samples/kafka-summit-2021-scst-kstream#1]
Soby, thanks for the presentation. I am new to Cloud Stream. I could not locate the kafka -> binder -> brokers in the code sample. How does Cloud Stream determine which kafka broker to connect to? 

```
cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka-kafka-bootstrap:9092
```
